name: ecommerce_app
description: A new Flutter project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_auth_web: ^6.1.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  # Background color of splash screen
  color: "#FFFFFF"
  # Splash logo
  image: assets/images/splash_logo.png
  android_gravity: center
  ios_content_mode: scaleAspectFit
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash_logo.png
  web: true
